settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: dynamic
    # 端口号
    port: 8099 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: true
  logger:
    # 日志存放路径
    path: logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: false
  jwt:
    # token 密钥，生产环境时及的修改
    secret: dynamic
    # token 过期时间 单位：秒
    #默认过期时间 5个小时
    timeout: 180000
  database:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:root123456@tcp(127.0.0.1:3306)/dynamic_demo?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
#    source: root:@tcp(127.0.0.1:3306)/dynamic?charset=utf8&parseTime=True&loc=Local&timeout=8000ms
  gen:
    # 代码生成读取的数据库名称
    dbname: dynamic
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../go-admin-ui/src
  extend: # 扩展项使用说明
    work: "/data/universe/"
    domain: "http://localhost:8099"
    imageBase: "image" #所有照片的基础目录
    wxLeader: #帮主端
      appid: "wx9e7c2f2a95287bc8"
      secret: "ea44bdfcbd19e235429eb53fa4070dd1"
    wxUser: #客户端
      appid: "wxed881f27a48289ed"
      secret: "bf26c5fed126b3bd384d8572331706d4"
    wxOfficial: #公众号
      appid: "wx5aa90ff822a6c59b"
      secret: "b50e5094497df0203f390761c0e4a542"
    fyPayClient: #客户端支付
      inscd: "08K0054880" #机构号
      payDomain: "https://spay-mc.fuioupay.com/wxPreCreate"
      paySearch: "https://spay-mc.fuioupay.com/commonQuery"
      mchntcd:  "0007910F5902365"
      orderRandom: "hfWUxQiqPx"
      openId: "o5TLF5YfLbL97r50xA157B9GOR3k"
  cache:
    memory: ''
  queue:
    memory:
      poolSize: 100
  locker:
    redis: